gitOps:
  app: argocd
ingress:
  host: 35.227.123.210.nip.io
  classname: contour
image: index.docker.io/vfarcic/cncf-demo
tag: v0.0.1
templates: helm
crossplane:
  destination: aws
production:
  azure:
    resourceGroup: dot-20240123133515
    location: eastus
  google:
    projectId: dot-20240812152736
