{{- if and (.Values.progressiveDelivery.enabled) (eq .Values.progressiveDelivery.type "argo-rollouts") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "name" . }}
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: {{ template "name" . }}-canary
      stableService: {{ template "name" . }}-primary
      trafficRouting:
        istio:
          virtualServices:
            - name: {{ template "name" . }}-1
              routes:
                - primary
            - name: {{ template "name" . }}-2
              routes:
                - secondary
      analysis:
        templates:
          - templateName: success-rate
            clusterScope: true
        startingStep: 2
        args:
          - name: service-name
            value: {{ template "name" . }}-canary.production.svc.cluster.local
      steps:
        - setWeight: 20
        - pause: {duration: 60}
        - setWeight: 40
        - pause: {duration: 60}
        - setWeight: 60
        - pause: {duration: 60}
        - setWeight: 80
        - pause: {duration: 60}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name:  {{ template "name" . }}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ template "name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ template "name" . }}-canary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name:  {{ template "name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name:  {{ template "name" . }}-primary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name:  {{ template "name" . }}
{{- end }}
