{{- if and (.Values.progressiveDelivery.enabled) (eq .Values.progressiveDelivery.tool "argo-rollouts") (.Values.serviceMesh.enabled) (eq .Values.serviceMesh.tool "istio") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "name" . }}
spec:
  replicas: 3
  strategy:
    canary:
      canaryService: {{ template "name" . }}-canary
      stableService: {{ template "name" . }}-stable
      trafficRouting:
        istio:
          virtualServices:
            - name: {{ template "name" . }}-1
              routes:
                - primary
            - name: {{ template "name" . }}-2
              routes:
                - secondary
      analysis:
        templates:
          - templateName: success-rate
            clusterScope: true
        startingStep: 2
        args:
          - name: service-name
            value: cncf-demo-canary.production.svc.cluster.local
      steps:
        - setWeight: 20
        - pause: {duration: 60}
        - setWeight: 40
        - pause: {duration: 60}
        - setWeight: 60
        - pause: {duration: 60}
        - setWeight: 80
        - pause: {duration: 60}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "name" . }}
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "name" . }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "name" . }}-gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-canary
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-stable
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ template "name" . }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "name" . }}-1
spec:
  gateways:
    - {{ template "name" . }}-gateway
  hosts:
    - {{ .Values.serviceMesh.gatewayHost }}
  http:
    - name: primary
      route:
        - destination:
            host: {{ template "name" . }}-stable
            port:
              number: 8080
          weight: 100
        - destination:
            host: {{ template "name" . }}-canary
            port:
              number: 8080
          weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "name" . }}-2
spec:
  gateways:
    - {{ template "name" . }}-gateway
  hosts:
    - {{ .Values.serviceMesh.gatewayHost }}
  http:
    - name: secondary
      route:
        - destination:
            host: {{ template "name" . }}-stable
            port:
              number: 8080
          weight: 100
        - destination:
            host: {{ template "name" . }}-canary
            port:
              number: 8080
          weight: 0
{{- end }}
