{{- if and (.Values.progressiveDelivery.enabled) (eq .Values.progressiveDelivery.type "flagger") }}
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ template "name" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "name" . }}
  service:
    port: 8080
    targetPort: 8080
    gateways:
      - {{ template "name" . }}-gateway
    hosts:
      - {{ .Values.istio.host }}
    trafficPolicy:
      tls:
        mode: DISABLE
  analysis:
    interval: 1m
    threshold: 2
    maxWeight: 80
    stepWeight: 20
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 95
        interval: 1m
{{- end }}
