{{- if and (.Values.progressiveDelivery.enabled) (.Values.istio.enabled) }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "name" . }}-gateway
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
{{- end }}
