apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: silly-demo
spec:
  components:
  - name: silly-demo
    type: app-backend
    properties:
      image: ghcr.io/vfarcic/cncf-demo-app
      tag: FIXME
      port: 8080
      host: silly-demo.135.237.0.239.nip.io
      ingressClassName: contour
      db:
        secret: silly-demo-db-20250107192103
