---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: containerssh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    repoURL: https://github.com/vfarcic/cncf-demo
    targetRevision: HEAD
    path: containerssh
  destination:
    server: https://kubernetes.default.svc
    namespace: containerssh
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
