---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.2.0"
    helm:
      releaseName: loki
      parameters:
        - name: loki.commonConfig.replication_factor
          value: "1"
        - name: loki.storage.type
          value: filesystem
        - name: loki.auth_enabled
          value: "false"
        - name: singleBinary.replicas
          value: "1"
        - name: deploymentMode
          value: SingleBinary
        - name: backend.replicas
          value: "0"
        - name: read.replicas
          value: "0"
        - name: write.replicas
          value: "0"
        - name: loki.useTestSchema
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
