apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure
spec:
  provider:
    azurekv:
      tenantId: e82964cf-adc2-4086-b7c2-bfbc1601d491
      vaultUrl: https://cncf-demo-20240123182909.vault.azure.net
      authSecretRef:
        clientId:
          name: azure-secret-sp
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          namespace: external-secrets
          key: ClientSecret
