---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hadlamp
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://headlamp-k8s.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hadlamp
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: hadlamp
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: hadlamp
        namespace: flux-system
  releaseName: hadlamp
  targetNamespace: hadlamp
  install:
    createNamespace: true
