---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: 1.21.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  releaseName: istio-base
  targetNamespace: istio-system
  install:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: 1.21.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  releaseName: istiod
  targetNamespace: istio-system
  install:
    createNamespace: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: 1.21.2
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  releaseName: gateway
  targetNamespace: istio-system
  install:
    createNamespace: true