---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kubearmor
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubearmor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubearmor
  install:
    createNamespace: true
