---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kyverno.github.io/kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 3.2.5
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  releaseName: kyverno
  targetNamespace: kyverno
  install:
    createNamespace: true
