---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfga
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: openfga
      version: "0.1.39"
      sourceRef:
        kind: HelmRepository
        name: openfga
        namespace: flux-system
  values:
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: openfga.35.229.65.41.nip.io
          paths:
            - path: /
              pathType: ImplementationSpecific
    replicaCount: 1
  releaseName: openfga
  targetNamespace: openfga
  install:
    createNamespace: true
