---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paralus
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ztka
      version: 0.2.6
      sourceRef:
        kind: HelmRepository
        name: paralus
        namespace: flux-system
  values:
    fqdn:
      domain: paralus.acme.com
    ingress:
      className: traefik
  releaseName: paralus
  targetNamespace: paralus
  install:
    createNamespace: true
