---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "57.2.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.127.0.0.1.nip.io
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.127.0.0.1.nip.io
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: istiod
            kubernetes_sd_configs:
              - role: endpoints
                namespaces:
                  names:
                    - istio-system
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                action: keep
                regex: istiod;http-monitoring
          - job_name: 'envoy-stats'
            metrics_path: /stats/prometheus
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: '.*-envoy-prom'
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    createNamespace: true
