---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "57.2.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.127.0.0.1.nip.io
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.127.0.0.1.nip.io
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  install:
    createNamespace: true
