apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AppScaling
metadata:
  name: dot-app-scaling
spec:
  match:
    kinds:
      - apiGroups: ["core.oam.dev"]
        kinds: ["Application"]
    namespaces: ["production"]
  parameters:
    min: 2
