apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AppScaling
metadata:
  name: dot-app-scaling
spec:
  match:
    kinds:
      - apiGroups: ["devopstoolkit.live"]
        kinds: ["AppClaim", "App"]
    namespaces: ["production"]
  parameters:
    min: 2
