#@ load("@ytt:data", "data")

#@ if data.values.db.enabled.crossplane.local or data.values.db.enabled.crossplane.google or data.values.db.enabled.crossplane.aws or data.values.db.enabled.crossplane.azure:
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: #@ data.values.name
spec:
  id: #@ data.values.db.id
  compositionSelector:
    matchLabels:
      #@ if/end data.values.db.enabled.crossplane.local:
      provider: local-k8s
      #@ if/end data.values.db.enabled.crossplane.google:
      provider: google
      #@ if/end data.values.db.enabled.crossplane.azure:
      provider: azure
      #@ if/end data.values.db.enabled.crossplane.aws:
      provider: aws
      db: postgresql
  parameters:
    #@ if/end data.values.db.enabled.crossplane.aws:
    version: "16.2"
    #@ if/end data.values.db.enabled.crossplane.local or data.values.db.enabled.crossplane.google or data.values.db.enabled.crossplane.azure:
    version: "11"
    size: #@ data.values.db.size
    databases:
    - #@ data.values.db.id
#@ end

#@ if data.values.db.enabled.crossplane.google or data.values.db.enabled.crossplane.aws or data.values.db.enabled.crossplane.azure:

#@ if data.values.db.insecure:

---
apiVersion: v1
kind: Secret
metadata:
  name: #@ data.values.db.id + "-password"
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=

#@ else:

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: #@ data.values.db.id + "-password"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    #@ if/end data.values.db.enabled.crossplane.google:
    name: google
    #@ if/end data.values.db.enabled.crossplane.azure:
    name: azure
    #@ if/end data.values.db.enabled.crossplane.aws:
    name: aws
  target:
    name: #@ data.values.db.id + "-password"
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: production-postgresql

#@ end

#@ end
