#@ load("@ytt:data", "data")

#@ if data.values.schemahero.enabled:
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: #@ data.values.name
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  immediateDeploy: true
  connection:
    postgres:
      host:
        #@ if data.values.db.enabled.helm:
        value: postgresql
        #@ elif data.values.db.enabled.crossplane.local:
        value: #@ data.values.db.id + "-postgresql"
        #@ else:
        valueFrom:
          secretKeyRef:
            name: #@ data.values.db.id
            key: endpoint
        #@ end
      user:
        #@ if data.values.db.enabled.helm or data.values.db.enabled.crossplane.local:
        value: postgres
        #@ elif data.values.db.enabled.crossplane.aws:
        value: masteruser
        #@ else:
        valueFrom:
          secretKeyRef:
            name: #@ data.values.db.id
            key: username
        #@ end
      password:
        valueFrom:
          secretKeyRef:
            #@ if data.values.db.enabled.helm:
            name: postgresql
            key: postgres-password
            #@ elif data.values.db.enabled.crossplane.local:
            name: #@ data.values.db.id + "-postgresql"
            key: postgres-password
            #@ else:
            name: #@ data.values.db.id
            key: password
            #@ end
      port:
        value: "5432"
      dbname:
        #@ if data.values.db.enabled.helm or data.values.db.enabled.crossplane.local:
        value: #@ data.values.name
        #@ else:
        value: #@ data.values.db.id
        #@ end
      sslmode:
        value: prefer

---

apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: #@ data.values.name + "-videos"
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  database: #@ data.values.db.id
  name: videos
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
#@ end
